## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-kafka-exporter
  name: test-kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kafka-exporter
  template:
    metadata:
      labels:
        app: test-kafka-exporter
    spec:
      containers:
      - image: bitnami/kafka-exporter
        name: kafka-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-kafka-exporter
  name: test-kafka-exporter
spec:
  ports:
  - port: 9308
    protocol: TCP
    targetPort: 9308
  selector:
    app: test-kafka-exporter
  sessionAffinity: None
  type: ClusterIP
